ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
device_name=Bina-Camera
device_type=1-0050F204-1
driver_param=use_p2p_group_interface=1

# P2P/WiFi Direct settings
# GO intent 15 = always be the Group Owner (access point)
p2p_go_intent=15
p2p_go_ht40=1
p2p_go_max_inactivity=0

# Regulatory domain - change to your country code
country=IL
